### PR TITLE
release version 0.9.8 for buster on revpi devices

### PR DESCRIPTION
**Pull request by zhan-kunbus**

### CODE REVIEW

**Review by iluminat23 — CHANGES_REQUESTED** [review]
Don't merge the branch (revpi/upstream), merge the tag!

**Comment by zhan-kunbus** [comment]
> Don't merge the branch (revpi/upstream), merge the tag!

good catch

**Review by iluminat23 — APPROVED** [review]

**Comment by iluminat23** [comment]
You can't merge this in the github UI!
merge the branch on the CLI with --ff-only and push the master branch

**Comment by zhan-kunbus** [comment]
> You can't merge this in the github UI! merge the branch on the CLI with --ff-only and push the master branch

I will do it in this way.
But just to ask, are you mean to keep the tag available?  actually, the tag has to re-create anyway.

**Comment by iluminat23** [comment]
Which tag?

**Pull request merged**
